import localFont from "next/font/local";
import "./globals.css";
import AppProviders from "./providers";
import { Metadata } from "next";

const literata = localFont({
    src: "../../public/fonts/literata-variable.ttf",
    variable: "--font-literata",
    display: "swap",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${literata.variable} antialiased`}>
                <AppProviders>{children}</AppProviders>
            </body>
        </html>
    );
}
